version: '3'

services:

  db:
    container_name: exam_db
    image: postgres
    hostname: db
    volumes:
      - ../volume/db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "54321:5432"
    networks: 
      - default
  pgadmin:
    container_name: pgadmin_container
    hostname: pgadmin
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: "mikimiki55550@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ../volume/pg:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: on-failure
    networks:
      - default
  examapi:
    build: .
    ports:
      - 5000:5000
    networks: 
      - default
    container_name: 
      examapi 
    depends_on: 
      - db
networks:
  default:
    driver: bridge
